---
title: "splice contrast"
subtitle: ""
author: ""
output:
  xaringan::moon_reader:
    seal: FALSE
    lib_dir: libs
    css: [default, hygge, ninjutsu]
    nature:
      ratio: 16:9
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---



```{r, include = F}
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(fig.width = 6, message = FALSE, warning = FALSE, comment = "", cache = F)
library(flipbookr)
library(tidyverse)
load("current_image.Rdata")
```


```{r, echo = F, eval = FALSE , message = F, warning = F}
xaringanExtra::use_share_again()
```


```{r the_chunk, include = F}
contrast <- function(colour) {
  out   <- rep("grey20", length(colour))
  light <- farver::get_channel(colour, "l", 
                               space = "hcl")
  out[light < 50] <- "grey80"
  out
}

aes(colour = after_scale(contrast(fill))) ->
  aes_colour_autocontrast_after_fill

library(tidyverse)
cor(mtcars) |>
  as.data.frame() |>
  tibble::rownames_to_column("row") |>
  pivot_longer(-row, names_to = "col") |>
  ggplot(aes(row, col)) +
  geom_raster() +
  aes(fill = value) + 
  geom_text(aes(label = round(value, 2)), size = 3) +
  coord_equal() +
  aes_colour_autocontrast_after_fill + 
  scale_fill_viridis_c(direction =  1) +
  scale_fill_viridis_c(direction = -1)
```

`r chunk_reveal(chunk_name = "the_chunk", break_type = "auto")`



```{css, eval = TRUE, echo = FALSE}
.remark-code{line-height: 1.5; font-size: 80%}

@media print {
  .has-continuation {
    display: block;
  }
}

code.r.hljs.remark-code{
  position: relative;
  overflow-x: hidden;
}


code.r.hljs.remark-code:hover{
  overflow-x:visible;
  width: 500px;
  border-style: solid;
}
```

